FROM cgr.dev/chainguard/bash:latest AS base

ARG HELM_UNITTEST_PACKAGE=https://github.com/helm-unittest/helm-unittest/releases/download/v1.0.1/helm-unittest-linux-amd64-1.0.1.tgz
ARG YQ_PACKAGE=https://github.com/mikefarah/yq/releases/download/v4.47.2/yq_linux_amd64.tar.gz

# Environment variables
ENV \
    HOME="/helm" 

RUN  \
    # Install Helm unittest plugin
    mkdir -p /tmp/hut /usr/local/bin && \
    curl ${HELM_UNITTEST_PACKAGE} -L -o /tmp/helm-unittest.tgz && \
    tar xvfz /tmp/helm-unittest.tgz -C /tmp/hut && \
    cp /tmp/hut/untt /usr/local/bin/helm-unittest && \
    rm -rf /tmp/helm-unittest.tar.gz /tmp/hut && \
    # install yq
    curl ${YQ_PACKAGE} -L -o /tmp/yq.tar.gz && \
    mkdir -p /tmp/yq && \
    tar xvfz /tmp/yq.tar.gz -C /tmp/yq && \
    cp -a /tmp/yq/yq_linux_amd64 /usr/local/bin/yq && \
    rm -rf /tmp/yq.tar.gz /tmp/yq && \
    # make all binaries executable
    chmod +x /usr/local/bin/*

RUN ls -al /usr/local/bin

FROM cgr.dev/chainguard/helm:latest-dev AS prod

USER root

COPY --from=base /usr/local/bin/ /usr/local/bin/

WORKDIR /helm

RUN chown -R 65532:0 /helm && \
    chmod -R g=u /helm

USER 65532