name: Dagger test

on:
  # ensure that it runs on all opened PR's
  pull_request:
    types: [opened, reopened]
  # run on every push
  push:

env:
  # The Dagger CLI uses the DAGGER_CLOUD_TOKEN environment variable to authenticate with Dagger Cloud
  DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
      - name: Generate and compile Helm module
        run: dagger functions -m helm/
      - name: Run module tests
        run: dagger -m tests/ call all
      - name: Run module integration tests
        env:
          TEST_HELM_REGISTRY_URL: ${{ secrets.TEST_HELM_REGISTRY_URL }}
          TEST_HELM_REGISTRY_REPOSITORY: ${{ secrets.TEST_HELM_REGISTRY_REPOSITORY }}
          TEST_HELM_REGISTRY_HELM_USER: ${{ secrets.TEST_HELM_REGISTRY_HELM_USER }}
          TEST_HELM_REGISTRY_HELM_PASSWORD: ${{ secrets.TEST_HELM_REGISTRY_HELM_PASSWORD }}
        run: |
            dagger -m tests/ \
              call helm-packagepush \
              --registry ${TEST_HELM_REGISTRY_URL} \
              --repository ${TEST_HELM_REGISTRY_REPOSITORY} \
              --username ${TEST_HELM_REGISTRY_HELM_USER} \
              --password env:TEST_HELM_REGISTRY_HELM_PASSWORD
      - name: Generate and compile ci module
        run: dagger -m ci/ functions
      - name: Generate and compile go examples module
        run: dagger -m helm/examples/go/ functions
      - name: Test shell examples
        run: |
            source helm/examples/shell/examples.sh
            helm_test
            helm_version
